Resources:
  BillingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      #TableName: ${self:custom.stage}-billings
      TableName: ${self:provider.environment.BILLINGS_TABLE}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}